<?php
$fn = function( $url ) {
  $domainpath = '';

  $fields = [
    [
      'id' => 0,
      'label' => 'Settings',
      'fields' => [
        [
          'name' => 'abId',
          'label' => 'id',
          'type' => 'text',
          'required' => true,
          'default' => '',
          'minLength' => '',
          'placeholder' => 'my_page',
          'sanitize' => true,
          'p' => __( 'The ID of the node.', 'cp-wordpress' ),
        ],
        [
          'name' => 'abTitle',
          'label' => __( 'Title', 'cp-wordpress' ),
          'type' => 'text',
          'required' => false,
          'default' => '',
          'minLength' => '',
          'placeholder' => 'My page',
          'p' => __( 'The text that will be visible in the Toolbar. Including html tags is allowed.', 'cp-wordpress' ),
        ],
        [
          'name' => 'abParent',
          'label' => 'Parent',
          'type' => 'text',
          'required' => false,
          'default' => '',
          'minLength' => '',
          'placeholder' => '',
          'sanitize' => true,
          'p' => __( 'The ID of the parent node.', 'cp-wordpress' ),
        ],
        [
          'name' => 'abHref',
          'label' => __( 'href', 'cp-wordpress' ),
          'type' => 'text',
          'required' => false,
          'default' => '',
          'minLength' => '',
          'placeholder' => 'http://mysite.com/my-page/',
          'p' => __( "The 'href' attribute for the link. If 'href' is not set the node will be a text node.", 'cp-wordpress' ),
        ],
        [
          'name' => 'abGroup',
          'label' => __( 'Group', 'cp-wordpress' ),
          'type' => 'checkbox',
          'required' => false,
          'default' => '',
          'minLength' => '',
          'placeholder' => '',
          'value' => 1,
          'p' => __( "This will make the node a group (node) if set to 'true'. Group nodes are not visible in the Toolbar, but nodes added to it are. <a href=\"https://codex.wordpress.org/Function_Reference/add_group\" target=\"_blank\">See add_group()</a>.", 'cp-wordpress' ),
        ],
      ],
    ],
    [
      'id' => 1,
      'label' => 'Meta',
      'fields' => [
        [
          'name' => 'abMetaHtml',
          'label' => __( 'HTML', 'cp-wordpress' ),
          'type' => 'text',
          'required' => false,
          'default' => '',
          'minLength' => '',
          'placeholder' => '',
          'class' => 'meta',
          'p' => __( "The html used for the node.", 'cp-wordpress' ),
        ],
        [
          'name' => 'abMetaClass',
          'label' => __( 'Class', 'cp-wordpress' ),
          'type' => 'text',
          'required' => false,
          'default' => '',
          'minLength' => '',
          'placeholder' => 'my-toolbar-page',
          'class' => 'meta',
          'p' => __( "The class attribute for the list item containing the link or text node.", 'cp-wordpress' ),
        ],
        [
          'name' => 'abMetaRel',
          'label' => __( 'rel', 'cp-wordpress' ),
          'type' => 'text',
          'required' => false,
          'default' => '',
          'minLength' => '',
          'placeholder' => '',
          'class' => 'meta',
          'p' => __( "The rel attribute.", 'cp-wordpress' ),
        ],
        [
          'name' => 'abMetaOnClick',
          'label' => __( 'onclick', 'cp-wordpress' ),
          'type' => 'text',
          'required' => false,
          'default' => '',
          'minLength' => '',
          'placeholder' => '',
          'class' => 'meta',
          'p' => __( "The onclick attribute for the link. This will only be set if the 'href' argument is present.", 'cp-wordpress' ),
        ],
        [
          'name' => 'abMetaTarget',
          'label' => __( 'target', 'cp-wordpress' ),
          'type' => 'text',
          'required' => false,
          'default' => '',
          'minLength' => '',
          'placeholder' => '',
          'class' => 'meta',
          'p' => __( "The target attribute for the link. This will only be set if the 'href' argument is present.", 'cp-wordpress' ),
        ],
        [
          'name' => 'abMetaTitle',
          'label' => __( 'Title', 'cp-wordpress' ),
          'type' => 'text',
          'required' => false,
          'default' => '',
          'minLength' => '',
          'placeholder' => '',
          'class' => 'meta',
          'p' => __( "The title attribute. Will be set to the link or to a div containing a text node.", 'cp-wordpress' ),
        ],
        [
          'name' => 'abMetaTabIndex',
          'label' => __( 'tabindex', 'cp-wordpress' ),
          'type' => 'number',
          'required' => false,
          'default' => '',
          'minLength' => '',
          'placeholder' => '',
          'class' => 'meta',
          'p' => __( "The tabindex attribute. Will be set to the link or to a div containing a text node.", 'cp-wordpress' ),
        ],
      ],
    ],
  ];

  return [
    'tabLayout' => 1,
    'fields' => $fields,
    'functionName' => 'custom_toolbar',
    'textDomain' => 'theme-slug',
    'title' => 'Admin bar menu',
    'description' => 'Create or add new items into the Admin bar.',
  ];
};
