<?php
$fn = function( $url ) {
  $domainpath = '';

  $fields = [
    [
      'name' => 'addTo',
      'label' => __( 'Add column to', 'cp-wordpress' ),
      'type' => 'select',
      'required' => true,
      'default' => '',
      'minLength' => '',
      'placeholder' => '',
      'hasLabels' => true,
      'default' => '_all_',
      'cssClass' => 'full-width',
      'options' => [
        '_all_' => __( 'All available post types', 'cp-wordpress' ),
        '_postpages' => __( 'Posts and Pages only', 'cp-wordpress' ),
        '_cpt_' => __( 'Custom post types only', 'cp-wordpress' ),
        '_posts_' => __( 'Posts only', 'cp-wordpress' ),
        '_pages_' => __( 'Pages only', 'cp-wordpress' ),
        '_custom_' => __( 'Custom post type', 'cp-wordpress' ),
      ],
      'p' => __( 'Select on which post type do you want to add your custom column.<br><span class="help-li"><strong>All available post types</strong> - Add the custom column to all the available post types, including posts and pages.</span><span class="help-li"><strong>Custom post types</strong> - Add the custom column only to the custom posts.</span><span class="help-li"><strong>Default post types</strong> - Add the custom column to posts and pages only.</span><span class="help-li"><strong>Custom post type slug</strong> - specify your own custom post type slug</span>', 'cp-wordpress' ),
    ],
    [
      'name' => 'customSlug',
      'label' => __( 'Custom post type name', 'cp-wordpress' ),
      'type' => 'text',
      'required' => false,
      'default' => '',
      'minLength' => '',
      'placeholder' => 'my_post_type',
      'sanitize' => true,
      'keepSpace' => true,
      'flex' => 66,
      'ifField' => 'addTo',
      'ifEqual' => '_custom_',
      'p' => __( 'Your own custom post type name.', 'cp-wordpress' ),
    ],
    [
      'name' => 'columnSlug',
      'label' => __( 'Column id', 'cp-wordpress' ),
      'type' => 'text',
      'required' => true,
      'default' => '',
      'minLength' => '',
      'placeholder' => 'my_column',
      'sanitize' => true,
      'p' => __( 'Your own column id.', 'cp-wordpress' ),
    ],
    [
      'name' => 'columnLabel',
      'label' => __( 'Column label', 'cp-wordpress' ),
      'type' => 'text',
      'required' => true,
      'default' => '',
      'minLength' => '',
      'placeholder' => 'My column',
      'flex' => 66,
      'cssClass' => 'full-width',
      'sanitize' => false,
      'p' => __( 'Your column label. HTML code is allowd into this field.', 'cp-wordpress' ),
    ],
    [
      'name' => 'columnPosition',
      'label' => __( 'Column position', 'cp-wordpress' ),
      'type' => 'select',
      'required' => true,
      'default' => '',
      'minLength' => '',
      'flex' => 33,
      'default' => '_end_',
      'cssClass' => 'full-width',
      'hasLabels' => true,
      'options' => [
        '_first_' => __( 'First column', 'cp-wordpress' ),
        'cb' => __( 'After checkbox', 'cp-wordpress' ),
        'title' => __( 'After title', 'cp-wordpress' ),
        'author' => __( 'After author', 'cp-wordpress' ),
        'categories' => __( 'After categories', 'cp-wordpress' ),
        'tags' => __( 'After tags', 'cp-wordpress' ),
        'comments' => __( 'After comments', 'cp-wordpress' ),
        'date' => __( 'After date', 'cp-wordpress' ),
        '_end_' => __( 'Last column', 'cp-wordpress' ),
      ],
      'p' => __( 'Set where do you want show your own column.', 'cp-wordpress' ),
    ],
    [
      'name' => 'columnSortable',
      'id' => 'sortable',
      'label' => __( 'Sortable', 'cp-wordpress' ),
      'type' => 'checkbox',
      'required' => false,
      'default' => '',
      'minLength' => '',
      'style' => 'switch',
      'value' => 1,
      'p' => __( 'If checked add the basic code to make the column sortable.', 'cp-wordpress' ),
    ],
    [
      'name' => 'metaKey',
      'label' => __( 'Meta key', 'cp-wordpress' ),
      'type' => 'text',
      'required' => false,
      'sanitize' => true,
      'default' => '',
      'minLength' => '',
      'placeholder' => 'meta_key',
      'ifField' => 'columnSortable',
      'ifEqual' => '1',
      'p' => __( 'The meta key name to be used for sorting the results', 'cp-wordpress' ),
    ],
  ];

  return [
    'fields' => $fields,
    'functionNameLabel' => 'Functions prefix',
    'functionName' => 'cp_',
    'textDomain' => 'text-domain',
    'layoutType' => 'column',
    'description' => 'Allos to add or remove custom columns to the post/page/cpt list page',
  ];
};
